version: 0.2

phases:
  install: 
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - aws iam create-group --group-name code-deploy
      - aws iam attach-group-policy --group-name code-deploy --policy-arn arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess --policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess --policy-arn arn:aws:iam::aws:policy/IAMFullAccess
      - aws s3 sync . s3://build.cdk/gongmo-front
      - npm install
  build:
    commands:
      - cdk deploy